### ISSUE TITLE
Admin Credentials

### ISSUE THREAD

**Issue by ChooeeTophee** [hanz02/hydraulic-jack#1]
Hi can you share the Admin credentials? the Admin dashboard cannot be configure because of the email and password. Thanks

**Comment by hanz02** [comment]
> Hi can you share the Admin credentials? the Admin dashboard cannot be configured because of the email and password. Thanks

Hi,  sorry here are the admin credentials. Will update them in the README.md soon. 

Email: user2140@hotmail.com
Password: hj1234567890

- If you are cloning this repo for your own use, please do be aware that this project was meant for a small scale personal project and is not suitable for actual development. I built this site solely for my college assignment purpose. The security and password encryption for the site is not actually well implemented. 

The payment gateway is actually a fake display payment gateway built for a college project and there is no authentication implemented. So do be aware as you go through them. And the purchase history section under the "user profile" page has not yet been completed due to the college project deadline, which means every time you make a payment the user profile purchase history section will still remain empty and won't display the products you have bought. 

Again, this project has not been fully completed yet, there are still modules left incomplete. I will finish them up when I am free with my degree study. Sorry for any inconveniences caused and I will immediately add this information as a disclaimer on README.md as well.

**Comment by ChooeeTophee** [comment]
Hi sorry, I just read your email today but thank you so much for the
effort, I am actually basing my college final project in web development
subject through your work but rest assured since I am giving you credits
responsibly and also this is for my college project only so rest assured
that I won't do something unethical from your project. Again Thank you so
much for the effort and for your help, you really saved me alot.
